export const OPEN_CATEGORY: string = 'OPEN_CATEGORY'
export const RESET_CATEGORY: string = 'RESET_CATEGORY'

export const ADD_SUBCATEGORY_FILTER: string = 'ADD_SUBCATEGORY_FILTER'
export const REMOVE_SUBCATEGORY_FILTER: string = 'REMOVE_SUBCATEGORY_FILTER'
export const ADD_PRICE_FILTER: string = 'ADD_PRICE_FILTER'
export const REMOVE_PRICE_FILTER: string = 'REMOVE_PRICE_FILTER'
export const CLEAR_FILTERS: string = 'CLEAR_FILTERS'
export const RESET_FILTERS: string = 'RESET_FILTERS'
