export const SHOW_FILTERS_LOADING = "SHOW_FILTERS_LOADING"
export const HIDE_FILTERS_LOADING = 'HIDE_FILTERS_LOADING'
export const SHOW_PRODUCTS_LOADING = 'SHOW_PRODUCTS_LOADING'
export const HIDE_PRODUCTS_LOADING = 'HIDE_PRODUCTS_LOADING'